AllCops:
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
